<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>TitanFx.DUnion.Common</PackageId>
    <Description>Some common discriminated union types, implemented by the DUnion source generator</Description>
    <IsPackable>True</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TitanFx.DUnion\TitanFx.DUnion.csproj">
      <PrivateAssets>all</PrivateAssets>
      <OutputItemType>Analyzer</OutputItemType>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>
</Project>
